# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EOWYHBWZ_Yq2fOY73V-MJVcR6XyBEVmZ
"""

import csv
import io

# 內嵌的CSV資料
csv_data = """Name,Math,Science,English
Alice,85,90,88
Bob,78,85,84
Charlie,92,88,91
"""

def read_csv_from_string(csv_string):
    file = io.StringIO(csv_string)
    reader = csv.reader(file)
    data = list(reader)
    return data

def calculate_averages(data):
    headers = data[0]
    num_columns = len(headers) - 1
    totals = [0] * num_columns
    counts = [0] * num_columns

    for row in data[1:]:
        for i in range(1, len(row)):
            totals[i-1] += float(row[i])
            counts[i-1] += 1

    averages = [totals[i] / counts[i] for i in range(num_columns)]
    return headers[1:], averages

def write_csv_to_string(headers, averages):
    output = io.StringIO()
    writer = csv.writer(output)
    writer.writerow(['Subject', 'Average'])
    for header, average in zip(headers, averages):
        writer.writerow([header, average])
    return output.getvalue()

# 讀取資料
data = read_csv_from_string(csv_data)

# 計算平均值
headers, averages = calculate_averages(data)

# 寫入結果到字串
output_csv_string = write_csv_to_string(headers, averages)

print('以下是處理後的CSV內容：')
print(output_csv_string)

